name = "bob"
compatibility_date = "2024-11-01"
pages_build_output_dir = "dist"

# 评论系统 KV 存储（Cloudflare Pages Functions 使用）
[[kv_namespaces]]
binding = "COMMENTS_KV"
id = "9311c2f035fb464e91de51ff52cee2e6"
